"""update foreign keys

Revision ID: 0a15eee1aeb2
Revises: fd38ee535c83
Create Date: 2025-03-18 15:43:32.619708

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "0a15eee1aeb2"
down_revision: Union[str, None] = "fd38ee535c83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "points", "regions", ["region_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "regions", "users", ["ceo_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "sale_codes", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(None, "trades", "users", ["user_id"], ["id"])
    op.create_foreign_key(
        None, "trades", "points", ["point_id"], ["point_id"]
    )
    op.create_foreign_key(
        None,
        "trades",
        "sale_codes",
        ["sale_code_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(None, "users", "points", ["point_id"], ["point_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_constraint(None, "trades", type_="foreignkey")
    op.drop_constraint(None, "trades", type_="foreignkey")
    op.drop_constraint(None, "trades", type_="foreignkey")
    op.drop_constraint(None, "sale_codes", type_="foreignkey")
    op.drop_constraint(None, "regions", type_="foreignkey")
    op.drop_constraint(None, "points", type_="foreignkey")
    # ### end Alembic commands ###
