"""update trades

Revision ID: 0be7317de26d
Revises: ff90e99420e5
Create Date: 2025-02-11 23:13:45.075735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be7317de26d'
down_revision: Union[str, None] = 'ff90e99420e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('sale_code_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trades', 'sale_codes', ['sale_code_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_column('trades', 'sale_code_id')
    # ### end Alembic commands ###
