"""add name in points model

Revision ID: 1d967f630574
Revises: 3b87147b327e
Create Date: 2025-02-04 23:06:16.728296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d967f630574'
down_revision: Union[str, None] = '3b87147b327e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'points', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'points', type_='unique')
    op.drop_column('points', 'name')
    # ### end Alembic commands ###
