"""add name in points model2

Revision ID: 2301ac1897fb
Revises: 1d967f630574
Create Date: 2025-02-04 23:08:52.759359

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2301ac1897fb"
down_revision: Union[str, None] = "1d967f630574"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_sale_code_id_fkey", "users", type_="foreignkey")
    op.drop_column("users", "sale_code_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("sale_code_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "users_sale_code_id_fkey", "users", "sale_codes", ["sale_code_id"], ["id"]
    )
    # ### end Alembic commands ###
