"""change sale_codes

Revision ID: 3b87147b327e
Revises: 09cc45a59765
Create Date: 2025-02-04 21:31:57.907871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b87147b327e'
down_revision: Union[str, None] = '09cc45a59765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_codes', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sale_codes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sale_codes', type_='foreignkey')
    op.drop_column('sale_codes', 'user_id')
    # ### end Alembic commands ###
