"""unique for trades

Revision ID: 3cc40989ada4
Revises: cf1f9ec24c13
Create Date: 2025-02-24 18:24:18.657486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc40989ada4'
down_revision: Union[str, None] = 'cf1f9ec24c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_point_sale_code_id', 'trades', ['sale_code_id', 'user_id', 'point_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_point_sale_code_id', 'trades', type_='unique')
    # ### end Alembic commands ###
