"""notifications model

Revision ID: 42298138ccdd
Revises: e40473f9fd8c
Create Date: 2025-02-25 01:53:42.168993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from app.bot.constants import NOTIFICATION_TYPE

# revision identifiers, used by Alembic.
revision: str = '42298138ccdd'
down_revision: Union[str, None] = 'e40473f9fd8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('notice_type', sqlalchemy_utils.types.choice.ChoiceType(NOTIFICATION_TYPE), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
