"""update sale_codes model

Revision ID: 64882a7d08f5
Revises: 3cc50383497e
Create Date: 2025-02-11 16:25:53.479051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64882a7d08f5'
down_revision: Union[str, None] = '3cc50383497e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'sale_codes', ['value'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sale_codes', type_='unique')
    # ### end Alembic commands ###
