"""add points name

Revision ID: 661e97867c12
Revises: 0a15eee1aeb2
Create Date: 2025-03-22 18:01:10.470593

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from app.points.models import same_as


# revision identifiers, used by Alembic.
revision: str = "661e97867c12"
down_revision: Union[str, None] = "0a15eee1aeb2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "points",
        sa.Column(
            "name", sa.String(), nullable=True, default=same_as("name")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("points", "name")
    # ### end Alembic commands ###
