"""cascade del schedules

Revision ID: 6a7e3d40850a
Revises: 6642d018f19e
Create Date: 2025-03-07 20:26:46.208553

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "6a7e3d40850a"
down_revision: Union[str, None] = "6642d018f19e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "schedules_user_id_fkey", "schedules", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "schedules", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "schedules", type_="foreignkey")
    op.create_foreign_key(
        "schedules_user_id_fkey", "schedules", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
