"""change user FK

Revision ID: 746edcd840ab
Revises: 64882a7d08f5
Create Date: 2025-02-11 21:12:46.681854

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "746edcd840ab"
down_revision: Union[str, None] = "64882a7d08f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_point_id_fkey", "users", type_="foreignkey")
    op.create_foreign_key(None, "users", "points", ["point_id"], ["point_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.create_foreign_key(
        "users_point_id_fkey", "users", "points", ["point_id"], ["id"]
    )
    # ### end Alembic commands ###
