"""change schedule atrr type

Revision ID: 7adbef240718
Revises: f3ea85bf4133
Create Date: 2025-02-25 23:50:14.130003

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7adbef240718"
down_revision: Union[str, None] = "f3ea85bf4133"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedules", "schedule")
    # op.alter_column('schedules', 'schedules',
    #            existing_type=postgresql.JSON(astext_type=sa.Text()),
    #            type_=sa.ARRAY(sa.Date()),
    #            existing_nullable=True)
    # # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "schedules",
        "schedule",
        existing_type=sa.ARRAY(sa.Date()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
