"""change user model attr for telegram_id

Revision ID: 980819cd0ea1
Revises: 8f12657ad884
Create Date: 2025-02-07 17:27:16.979660

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "980819cd0ea1"
down_revision: Union[str, None] = "8f12657ad884"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "tg_user_id", new_column_name="telegram_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "tg_user_id", new_column_name="telegram_id")
