"""delete orphan2

Revision ID: bbbe0f9bf92d
Revises: 1bc25d15d46f
Create Date: 2025-03-04 21:30:45.725270

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "bbbe0f9bf92d"
down_revision: Union[str, None] = "1bc25d15d46f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "unique_user_point_sale_code_id", "trades", type_="unique"
    )
    op.create_unique_constraint(
        "unique_sale_code_id", "trades", ["sale_code_id", "id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_sale_code_id", "trades", type_="unique")
    op.create_unique_constraint(
        "unique_user_point_sale_code_id",
        "trades",
        ["sale_code_id", "user_id", "point_id"],
    )
    # ### end Alembic commands ###
