"""add schedule attr

Revision ID: c5cecba5f1d2
Revises: 7adbef240718
Create Date: 2025-02-26 00:04:22.266753

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "c5cecba5f1d2"
down_revision: Union[str, None] = "7adbef240718"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedules", sa.Column("schedule", sa.ARRAY(sa.Date()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedules", "schedule")
    # ### end Alembic commands ###
