"""update salecodes model

Revision ID: cb2f1d8e3312
Revises: 661e97867c12
Create Date: 2025-03-24 15:07:53.028471

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "cb2f1d8e3312"
down_revision: Union[str, None] = "661e97867c12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "trades_sale_code_id_fkey", "trades", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "trades", "sale_codes", ["sale_code_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "trades", type_="foreignkey")
    op.create_foreign_key(
        "trades_sale_code_id_fkey",
        "trades",
        "sale_codes",
        ["sale_code_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
