"""ad uniq for scodes

Revision ID: ea193dac14c7
Revises: eb7c3be4bc70
Create Date: 2025-02-18 20:57:42.272658

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ea193dac14c7"
down_revision: Union[str, None] = "eb7c3be4bc70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_user_id_and_value", "sale_codes", ["user_id", "value"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "unique_user_id_and_value", "sale_codes", type_="unique"
    )
    # ### end Alembic commands ###
