"""update trades

Revision ID: eb7c3be4bc70
Revises: 0be7317de26d
Create Date: 2025-02-11 23:16:29.824413

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eb7c3be4bc70"
down_revision: Union[str, None] = "0be7317de26d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trades", "sale_code_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "trades", "point_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trades", "point_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "trades", "sale_code_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
