"""regions model

Revision ID: ebf089b5c279
Revises: 5707f4f25424
Create Date: 2025-03-15 01:19:06.089287

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "ebf089b5c279"
down_revision: Union[str, None] = "5707f4f25424"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "regions",
        sa.Column("ceo_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ceo_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column(
        "points", sa.Column("region_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "points", "regions", ["region_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "points", type_="foreignkey")
    op.drop_column("points", "region_id")
    op.drop_table("regions")
    # ### end Alembic commands ###
