"""change trade  FK

Revision ID: ff90e99420e5
Revises: 746edcd840ab
Create Date: 2025-02-11 21:58:25.505139

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ff90e99420e5"
down_revision: Union[str, None] = "746edcd840ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("trades_point_id_fkey", "trades", type_="foreignkey")
    op.create_foreign_key(None, "trades", "points", ["point_id"], ["point_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "trades", type_="foreignkey")
    op.create_foreign_key(
        "trades_point_id_fkey", "trades", "points", ["point_id"], ["id"]
    )
    # ### end Alembic commands ###
