services:
  main_bot:
    image: eliaswide/qr_trade_bot
    env_file:
      - main.env
    restart: on-failure
    ports:
      - "5000:5000"
    depends_on:
      - postgres_main

  postgres_main:
    image: postgres:latest
    env_file:
      - db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: